name: CI/CD Deployment

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_NAME="${{ vars.DOCKER_USERNAME }}/streamlit-portfolio:${{ github.sha }}"
        echo "Building Docker image: $IMAGE_NAME"
        docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ vars.DOCKER_USERNAME }}/streamlit-portfolio:${{ github.sha }}"
        echo "Pushing Docker image: $IMAGE_NAME"
        docker push $IMAGE_NAME
