name : CI/CD Deplyment
on: 
  push:
    branches:
      -  main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/streamlit-portfolio:v1 . 

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/streamlit-portfolio:v1
