name: CI/CD Deployment
on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Tag Docker Image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/portfolio"
        SHA_TAG="${IMAGE_NAME}:${{ github.sha }}"
        LATEST_TAG="${IMAGE_NAME}:latest"

        echo "Building Docker image: $SHA_TAG"
        docker build -t "$SHA_TAG" .

        echo "Tagging image as latest"
        docker tag "$SHA_TAG" "$LATEST_TAG"

    - name: Push Docker Image
      run: |
        docker push "${{ secrets.DOCKER_USERNAME }}/portfolio:${{ github.sha }}"
        docker push "${{ secrets.DOCKER_USERNAME }}/portfolio:latest"

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
        api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings
  gmail:  
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Send Email via Gmail
      uses: Raghul-M/gmail-sender-action@v1
      with:
          sender_email: ${{ secrets.GMAIL_SENDER }}
          app_password: ${{ secrets.GMAIL_APP_PASSWORD }}
          receiver_emails: ${{ secrets.RECIPIENTS }}
          template_path: "templates/index.html"
          subject: "Notification from GitHub Action"

